# Site settings
title: samjamead.github.io
email: samjamead@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Namaste friend! Sam Mead is training to be a physics teacher.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samjamead.github.io/" # the base hostname & protocol for your site
twitter_username: samjamead
github_username:  samjamead
plugins:
  - jekyll-redirect-from

# Build settings
author: samjamead@gmail.com
markdown: kramdown

# Defaults
defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
     author: Sam Mead
     layout: "post"
