# Site settings
title: Mead.fm
email: sam@mead.fm
description: > # this means to ignore newlines until "baseurl:"
  Namaste friend! Sam Mead is a web developer and startup helper in Perth, WA. This is a blog about startups, the environment, sport, Buddhism, and probably some other things. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mead.fm/" # the base hostname & protocol for your site
twitter_username: samjamead
github_username:  samjamead
gems:
  - jekyll-redirect-from

# Build settings
author: sam@mead.fm
markdown: kramdown

# Defaults
defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
     author: Sam Mead
     layout: "post"
