# Site settings
title: Mead.fm
email: sam@mead.fm
description: A blog about startups, the environment, sport, Buddhism, and probably some other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samjamead.com" # the base hostname & protocol for your site
twitter_username: samjamead
github_username:  samjamead
paginate: 5
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty

# Defaults
defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
     author: Sam Mead
     layout: "post"
